services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pacem-backend
    ports:
      - "8000:8000"
    volumes: 
      - ./apps/backend:/app/backend
    working_dir: /app/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
